import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
if not TELEGRAM_TOKEN:
    raise RuntimeError("❌ TELEGRAM_TOKEN not set")

SYMBOLS = [
    "BTC-USDT-SWAP", "ETH-USDT-SWAP", "TAO-USDT-SWAP",
    "LTC-USDT-SWAP", "SOL-USDT-SWAP", "BNB-USDT-SWAP",
    "XRP-USDT-SWAP", "LINK-USDT-SWAP", "ZEC-USDT-SWAP",
    "SUI-USDT-SWAP", "AVAX-USDT-SWAP", "AAVE-USDT-SWAP",
]

SCALP_TP = 0.025
SCALP_SL = 0.01

HFT_TP = 0.01
HFT_SL = 0.005

# ⏱ Cooldown (seconds)
SIGNAL_COOLDOWN = 15 * 60

MIN_CONFIDENCE = 60
